export const FACEBOOK_LOGIN_TOKEN = 'FACEBOOK_LOGIN_TOKEN';
export const FACEBOOK_LOGIN_ID = 'FACEBOOK_LOGIN_ID';
export const FACEBOOK_USER_DETAILS = 'FACEBOOK_USER_DETAILS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

export const USER_LOGIN_SESSION = 'USER_LOGIN_SESSION';
export const USER_DETAILS = 'USER_DETAILS';

export const GOOGLE_NEARBY_PLACES_TO_CONFIRM = 'GOOGLE_NEARBY_PLACES_TO_CONFIRM';
export const GOOGLE_LOCATION_API_CALL_REQUIRED = 'GOOGLE_LOCATION_API_CALL_REQUIRED';
export const NEARBY_PLACES_REFRESH_REQUIRED = 'NEARBY_PLACES_REFRESH_REQUIRED';

export const USER_CURRENT_LOCATION_BY_PHONE = 'USER_CURRENT_LOCATION_BY_PHONE';
export const USER_CONFIRMED_LOCATION = 'USER_CONFIRMED_LOCATION';
export const USER_NEARBY_PLACES = 'user_nearby_places';
export const USERS_AT_SELECTED_PLACE = 'USERS_AT_SELECTED_PLACE';
export const PLACE_DETAILS = 'PLACE_DETAILS';

export const SEARCH_GENDER_CHANGED = 'SEARCH_GENDER_CHANGED';
export const AGE_CHANGED = 'AGE_CHANGED';
export const DISTANCE_CHANGED = 'DISTANCE_CHANGED';
export const SHOW_ME_CHANGED = 'SHOW_ME_CHANGED';
export const SHOW_AGE_CHANGED = 'SHOW_AGE_CHANGED';

export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';

export const TOP_CROWDED_PLACES = 'TOP_CROWDED_PLACES';
